# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here

np.version.version
print("la versión es", np.version.version)




la versión es 1.24.3


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.random((2,3,5))
a


# El paréntesis de fuera, es que es una función. El de dentro es que es una tupla

array([[[0.2009703 , 0.36487833, 0.49989685, 0.55351613, 0.67461529],
        [0.68663092, 0.50401361, 0.70315578, 0.97561038, 0.85114617],
        [0.68997372, 0.83448763, 0.76045236, 0.12403124, 0.44323006]],

       [[0.31842947, 0.92527859, 0.70936683, 0.75514941, 0.03006585],
        [0.39619322, 0.12986757, 0.25571796, 0.30683772, 0.59575516],
        [0.59805867, 0.62687285, 0.80090192, 0.89012554, 0.12214101]]])

In [4]:
# Method 2 en vez e random, rand y no meto una tupla sino int
a2= np.random.rand(2,3,5)

a2

array([[[0.91496454, 0.6367238 , 0.02750314, 0.04295748, 0.89383701],
        [0.43586331, 0.61754533, 0.61364266, 0.75508634, 0.73197442],
        [0.56046429, 0.4411933 , 0.97522729, 0.18098172, 0.19758682]],

       [[0.8078155 , 0.63106497, 0.3416993 , 0.23623986, 0.41020247],
        [0.10277616, 0.47659889, 0.76937516, 0.00299069, 0.09674656],
        [0.18124845, 0.16306631, 0.53574144, 0.67385849, 0.22445522]]])

In [5]:
# Method 3 en vez de random, randomom_sample
a3=np.random.random_sample((2,3,5))
a3

array([[[0.0398671 , 0.69059607, 0.14134115, 0.03035606, 0.43315732],
        [0.38553094, 0.38469581, 0.35426793, 0.73198532, 0.32070546],
        [0.56592393, 0.91990384, 0.22242336, 0.65482606, 0.93693116]],

       [[0.07920103, 0.33995857, 0.60538109, 0.6253042 , 0.7549574 ],
        [0.07238913, 0.40635844, 0.63868162, 0.76917478, 0.26170041],
        [0.20329285, 0.24468254, 0.04582399, 0.3312028 , 0.77064912]]])

#### 4. Print *a*.


In [6]:
# your code here
print (a)

[[[0.2009703  0.36487833 0.49989685 0.55351613 0.67461529]
  [0.68663092 0.50401361 0.70315578 0.97561038 0.85114617]
  [0.68997372 0.83448763 0.76045236 0.12403124 0.44323006]]

 [[0.31842947 0.92527859 0.70936683 0.75514941 0.03006585]
  [0.39619322 0.12986757 0.25571796 0.30683772 0.59575516]
  [0.59805867 0.62687285 0.80090192 0.89012554 0.12214101]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here  
b = np.ones((5,2,3))

#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
b.size == a.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here
a+b #se podría poner también np.add(a,b)
#is not possible due the difference in the number of files/columns; the number of columns in the first one shall be the same as the number od files in the second one.

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here

#si pongo b.T me da una e 3x2x5 

 #hay que cambiar el axis pa que salga de las dimensiones que queremos; axes=(1, 2, 0) es cambiar de la orginal (0,1,2)a como queremos reestructurarla.
c=b.transpose(1,2,0)
print (c)
c.shape

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here

d= a+c
d

# the number of columns in the first one is the same as the number od files in the second one.

print(a, a.shape)
print(c, c.shape)
print(d, d.shape)

[[[0.2009703  0.36487833 0.49989685 0.55351613 0.67461529]
  [0.68663092 0.50401361 0.70315578 0.97561038 0.85114617]
  [0.68997372 0.83448763 0.76045236 0.12403124 0.44323006]]

 [[0.31842947 0.92527859 0.70936683 0.75514941 0.03006585]
  [0.39619322 0.12986757 0.25571796 0.30683772 0.59575516]
  [0.59805867 0.62687285 0.80090192 0.89012554 0.12214101]]] (2, 3, 5)
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]] (2, 3, 5)
[[[1.2009703  1.36487833 1.49989685 1.55351613 1.67461529]
  [1.68663092 1.50401361 1.70315578 1.97561038 1.85114617]
  [1.68997372 1.83448763 1.76045236 1.12403124 1.44323006]]

 [[1.31842947 1.92527859 1.70936683 1.75514941 1.03006585]
  [1.39619322 1.12986757 1.25571796 1.30683772 1.59575516]
  [1.59805867 1.62687285 1.80090192 1.89012554 1.12214101]]] (2, 3, 5)


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here
print(a, "\n")

print("This is d\n" , d)

#each element in d is the same as the element in a plus 1

[[[0.2009703  0.36487833 0.49989685 0.55351613 0.67461529]
  [0.68663092 0.50401361 0.70315578 0.97561038 0.85114617]
  [0.68997372 0.83448763 0.76045236 0.12403124 0.44323006]]

 [[0.31842947 0.92527859 0.70936683 0.75514941 0.03006585]
  [0.39619322 0.12986757 0.25571796 0.30683772 0.59575516]
  [0.59805867 0.62687285 0.80090192 0.89012554 0.12214101]]] 

This is d
 [[[1.2009703  1.36487833 1.49989685 1.55351613 1.67461529]
  [1.68663092 1.50401361 1.70315578 1.97561038 1.85114617]
  [1.68997372 1.83448763 1.76045236 1.12403124 1.44323006]]

 [[1.31842947 1.92527859 1.70936683 1.75514941 1.03006585]
  [1.39619322 1.12986757 1.25571796 1.30683772 1.59575516]
  [1.59805867 1.62687285 1.80090192 1.89012554 1.12214101]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here
e =a*c #es lo mimsmo que np.mutiply(a,c)

e


array([[[0.2009703 , 0.36487833, 0.49989685, 0.55351613, 0.67461529],
        [0.68663092, 0.50401361, 0.70315578, 0.97561038, 0.85114617],
        [0.68997372, 0.83448763, 0.76045236, 0.12403124, 0.44323006]],

       [[0.31842947, 0.92527859, 0.70936683, 0.75514941, 0.03006585],
        [0.39619322, 0.12986757, 0.25571796, 0.30683772, 0.59575516],
        [0.59805867, 0.62687285, 0.80090192, 0.89012554, 0.12214101]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here
e is a

#No, it is not the same eventhoug the values are the same. Ocupan distinto espacio de memoria


False

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here
d_max= d.max()
d_min=d.min()
d_mean=d.mean()
print ("min",d_min)
print ("max",d_max)
print ("mean",d_mean)


min 1.0300658496191604
max 1.975610380469418
mean 1.5442456848684254


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here 

f=np.empty((2,3,5))  #coge el último del que tiene memoria, no me lo da lleno de ceros. Solo me da ceros si lo hago al principio del todo.f está vacío
f


array([[[0.2009703 , 0.36487833, 0.49989685, 0.55351613, 0.67461529],
        [0.68663092, 0.50401361, 0.70315578, 0.97561038, 0.85114617],
        [0.68997372, 0.83448763, 0.76045236, 0.12403124, 0.44323006]],

       [[0.31842947, 0.92527859, 0.70936683, 0.75514941, 0.03006585],
        [0.39619322, 0.12986757, 0.25571796, 0.30683772, 0.59575516],
        [0.59805867, 0.62687285, 0.80090192, 0.89012554, 0.12214101]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [45]:
# your code here #me falta meter el d=dmin
np.where(d == d_mean, 50, np.where(d< d_min, 25, np.where(d>d_mean,75, np.where(d==d_max,100,0)))) # con la condicion me das un 1, else 0

array([[[75,  0,  0,  0,  0],
        [ 0, 75,  0,  0,  0],
        [ 0, 75, 75,  0,  0]],

       [[ 0, 75, 75, 75,  0],
        [ 0, 75,  0,  0, 75],
        [ 0, 75, 75,  0, 75]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [46]:
# your code here
print (d)
print(f)

[[[1.98319586 1.38312442 1.04528449 1.34847242 1.27292669]
  [1.42051682 1.73272644 1.46057832 1.13743817 1.08831834]
  [1.27298878 1.89608064 1.82008106 1.12689552 1.4213532 ]]

 [[1.00925844 1.78454418 1.87337737 1.97072684 1.33311005]
  [1.21585971 1.50076915 1.4489035  1.33481848 1.6698966 ]
  [1.13089982 1.51503955 1.69340701 1.03476078 1.96088428]]]
[[[0.98319586 0.38312442 0.04528449 0.34847242 0.27292669]
  [0.42051682 0.73272644 0.46057832 0.13743817 0.08831834]
  [0.27298878 0.89608064 0.82008106 0.12689552 0.4213532 ]]

 [[0.00925844 0.78454418 0.87337737 0.97072684 0.33311005]
  [0.21585971 0.50076915 0.4489035  0.33481848 0.6698966 ]
  [0.13089982 0.51503955 0.69340701 0.03476078 0.96088428]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [50]:
# your code here: esto está mal
np.where(d == d_mean, "A", np.where(d< d_min, "B", np.where(d>d_mean,"C", np.where(d==d_max,"D","E"))))

array([[['C', 'E', 'E', 'E', 'E'],
        ['E', 'C', 'E', 'E', 'E'],
        ['E', 'C', 'C', 'E', 'E']],

       [['E', 'C', 'C', 'C', 'E'],
        ['E', 'C', 'E', 'E', 'C'],
        ['E', 'C', 'C', 'E', 'C']]], dtype='<U1')

In [48]:
#primero convertir a string para que salga bien np.array(str(f))




array('[[[0.98319586 0.38312442 0.04528449 0.34847242 0.27292669]\n  [0.42051682 0.73272644 0.46057832 0.13743817 0.08831834]\n  [0.27298878 0.89608064 0.82008106 0.12689552 0.4213532 ]]\n\n [[0.00925844 0.78454418 0.87337737 0.97072684 0.33311005]\n  [0.21585971 0.50076915 0.4489035  0.33481848 0.6698966 ]\n  [0.13089982 0.51503955 0.69340701 0.03476078 0.96088428]]]',
      dtype='<U357')